### ISSUE TITLE
validRef() is incorrectly implemented

### ISSUE THREAD

**Issue by steveblackburn** [mmtk/mmtk-jikesrvm#12]
The Rust implementation of MemoryManager.validRef() does not perform the checks that the original version does.   Specifically, the original version checks the integrity of the referenced object (according to the JikesRVM object model -- ie that the TIB is sound, etc), which the Rust version is not doing.

The only part that should be Rust-MMTk-specific is the check to see whether the referent object is in a currently mapped space.   The remaining logic (checking the TIB etc) should be executed for both cases since it has nothing to do with the memory manager.

**Comment by javadamiri** [comment]
I can't find `valid_ref()` in Rust MMTk's `memory_manager` module.
There are three functions which serve relevant purposes:

```
pub fn is_live_object(object: ObjectReference) -> bool;
pub fn is_mapped_object(object: ObjectReference) -> bool;
pub fn is_mapped_address(address: Address) -> bool;
```
and none of them perform the checks from `MemoryManager.validRef()`.

However, `MemoryManager.validRef()` in our JikesRVM fork calls `is_mapped_object()`, to check whether an object is in a currently mapped space, when on Rust MMTk.

So, I think this issue does not apply to the current RustMMTk/JikesRVM and can be closed.
What do you think @qinsoon ?

**Comment by qinsoon** [comment]
I think Steve referred to `validRef()` in JikesRVM. I looked at the implementation, it seems everything is the same as in Java MMTk except that we call into Rust MMTk for `is_mapped()`.

I feel this was an issue, but Steve fixed it in his commit to our JikesRVM fork. https://github.com/mmtk/jikesrvm/commit/65ee02bd38b8ed2d17f0bb8d1160ad9d1731c5b2#diff-937ada3144236a6d0cfe1216470696f0bef398eb115ca01da955e7f51500902c

**Comment by qinsoon** [comment]
If you agree with my guess above, you can close this issue.

**Comment by javadamiri** [comment]
Yes, I think you're right
