### ISSUE TITLE
Use asm! to replace llvm_asm!

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-jikesrvm#85]
`llvm_asm!` is going to be deprecated soon, and the new `asm!` (with new syntax) should be used for inline assembly. And `asm!` will be stabilised. We should migrate to `asm!` as soon as we can. Currently I am putting a `#![allow(deprecated)]` to the whole binding crate to allow the clippy warning about deprecated `llvm_asm!`.

**Comment by caizixian** [comment]
Closed in #86
